### ISSUE TITLE
fix: operator panic when reconnect fails after max retries

### ISSUE THREAD

**Issue by taturosati** [yetanotherco/aligned_layer#960]
Operator panics when unable to resubscribe to rpc after max retries are reached.

stack trace:

```
goroutine 61 [running]:
github.com/yetanotherco/aligned_layer/core/chainio.(*AvsSubscriber).SubscribeToNewTasks.func2()
        /root/aligned_layer/core/chainio/avs_subscriber.go:115 +0x5e
created by github.com/yetanotherco/aligned_layer/core/chainio.(*AvsSubscriber).SubscribeToNewTasks in goroutine 1
        /root/aligned_layer/core/chainio/avs_subscriber.go:112 +0x36a
```

**Comment by JuArce** [comment]
Addressed on https://github.com/yetanotherco/aligned_layer/issues/1728
